# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-11-19 03:23
from __future__ import unicode_literals
import datetime
from django.db import migrations, transaction


def move_dates_over(apps, schema_editor):
    """Converts the datetime field into a date field
    """
    with transaction.atomic():
        Menu = apps.get_model('menu', 'Menu')
        for menu in Menu.objects.all():
            try:
                if menu.created_date:
                    menu.created = menu.created_date.date()
                else:
                    menu.created = datetime.date.today()
                if menu.expiration_date:
                    menu.expiry = menu.expiration_date.date()
                menu.save()
            except Error as err:
                print("Menu Error: ", err)

    with transaction.atomic():
        Item = apps.get_model('menu', 'Item')
        for item in Item.objects.all():
            try:
                if item.created_date:
                    item.created = item.created_date.date()
                else:
                    item.created = datetime.date.today()
                item.save()
            except Error as err:
                print("Item Error: ", err)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191118_1919'),
    ]

    operations = [
        migrations.RunPython(move_dates_over),
    ]
