# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-11-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20191114_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
