# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-11-15 01:51
from __future__ import unicode_literals
import datetime
from django.db import migrations, transaction

def correct_dates(apps, schema_editor):
    with transaction.atomic():
        Menu = apps.get_model('menu', 'Menu')
        try:
            for menu in Menu.objects.all():
                if menu.created_date:
                    menu.created = menu.created_date.date()
                else:
                    menu.created_date = datetime.date.today()
                if menu.expiration_date:     
                    menu.expiry = menu.expiration_date.date()
                menu.save() 

            Item = apps.get_model('menu', 'Item')
            for item in Item.objects.all():
                if item.created_date:
                    item.created = item.created_date.date()
                else:
                    item.created = datetime.date.today()
                item.save()
        except Error as err:
            print("Error: ", err)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191115_1135'),
    ]

    operations = [
        migrations.RunPython(correct_dates),
    ]
